name: CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stretch

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      
    - name: Greeting
      run: echo Hello, world.

    - name: Print the Current Time
      run: date
